"""Execute raw-SQL Alembic migrations online or emit SQL offline.

Importing prepends the asset parent to sys.path and runs the selected mode.
Deployed modes read MIGRATION_DATABASE_URL; other modes load application
settings and use DATABASE_URL. No ORM metadata is available.
"""

import logging
import os
import sys
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.engine import make_url

from alembic import context

# Alembic executes env.py as a standalone script, so src/ must be
# added to sys.path for the config package to be importable.
ALEMBIC_DIR = Path(__file__).resolve().parent
SRC_DIR = ALEMBIC_DIR.parent

sys.path.insert(0, str(SRC_DIR))

# Migrations are raw SQL (op.execute), not autogenerated from ORM models,
# so there is no model metadata to diff against.
target_metadata = None


def _db_url() -> str:
    """Return a psycopg SQLAlchemy URL from the environment selected by ENV_STATE.

    Staging/production require MIGRATION_DATABASE_URL; other values import config
    and use DATABASE_URL. Only postgres:// and postgresql:// are accepted. Raises
    RuntimeError for a missing/unsupported URL; settings errors propagate.
    """
    env_state = os.environ.get("ENV_STATE", "dev")
    if env_state in {"staging", "production"}:
        url = os.environ.get("MIGRATION_DATABASE_URL", "")
        if not url:
            raise RuntimeError("MIGRATION_DATABASE_URL is required for deployed migrations")
    else:
        from config import settings  # noqa: PLC0415

        url = os.environ.get(
            "DATABASE_URL",
            settings.database_url.get_secret_value(),
        )

    for prefix in ("postgresql://", "postgres://"):
        if url.startswith(prefix):
            return "postgresql+psycopg://" + url[len(prefix) :]
    raise RuntimeError("Migration database URL must use postgresql:// or postgres://")


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL, no DB connection."""
    db_url = _db_url()

    context.configure(
        url=db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations transactionally through a new SQLAlchemy engine, then dispose it.

    Prints the password-masked URL and logs the resulting head; errors propagate.
    """
    db_url = _db_url()
    safe_db_url = make_url(db_url).render_as_string(hide_password=True)

    print(f"Alembic connecting to: {safe_db_url}")

    connectable = create_engine(db_url)
    try:
        with connectable.connect() as connection:
            context.configure(connection=connection, target_metadata=target_metadata)
            with context.begin_transaction():
                context.run_migrations()
            logging.getLogger("alembic.runtime.migration").info(
                "Migration completed; database heads: %s", context.get_context().get_current_heads()
            )
    finally:
        connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
