"""Alembic environment configuration.

Uses the same DATABASE_URL as the application via Pydantic Settings.
Runs migrations using raw SQL (no SQLAlchemy metadata).
"""
import sys
from pathlib import Path

from alembic import context
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url

# Alembic executes env.py as a standalone script, so src/ must be
# added to sys.path for the config package to be importable.
ALEMBIC_DIR = Path(__file__).resolve().parent        
SRC_DIR = ALEMBIC_DIR.parent                                  

sys.path.insert(0, str(SRC_DIR))


from config import settings # noqa: E402

# Migrations are raw SQL (op.execute), not autogenerated from ORM models,
# so there is no model metadata to diff against.
target_metadata = None

def _db_url() -> str:
    url = settings.database_url.get_secret_value()
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — emit SQL, no DB connection."""
    db_url = _db_url()

    context.configure(
        url=db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode — against a live connection."""
    db_url =  _db_url()
    safe_db_url = make_url(db_url).render_as_string(hide_password=True)

    print(f"Alembic connecting to: {safe_db_url}")

    connectable = create_engine(db_url)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
