"""Exact catalog-value contracts consumed by db_drift; dataclasses do not validate inputs.

Function source strings include SQL comments and are compared exactly.
Their public search blob uses title/access_level, a subset of
PUBLIC_DISCOVERY_FIELDS; the full blob uses only the concatenated
fields shown in its SQL. Editing these string literals changes the
runtime contract and requires a corresponding database migration.
"""

from dataclasses import dataclass
from typing import Literal

IdentityMode = Literal["", "a", "d"]
IndexMethod = Literal["btree", "gin"]
TriggerEnabledMode = Literal["O", "D", "R", "A"]
FunctionVolatility = Literal["i", "s", "v"]
FunctionParallelMode = Literal["u", "r", "s"]


@dataclass(frozen=True, slots=True)
class ColumnSpec:
    """Column type/default as PostgreSQL renders them; None means no default.

    identity is empty for no identity, a for GENERATED ALWAYS, or d for
    GENERATED BY DEFAULT.
    """

    pg_type: str
    nullable: bool
    default: str | None = None
    identity: IdentityMode = ""


@dataclass(frozen=True, slots=True)
class IndexKeySpec:
    """Ordered key expression/operator class with descending and NULL-ordering flags."""

    definition: str
    operator_class: str
    descending: bool = False
    nulls_first: bool = False


@dataclass(frozen=True, slots=True)
class IndexSpec:
    """Exact non-constraint index structure and readiness flags.

    keys and include_columns preserve order; predicate=None means no
    partial-index predicate. Expressions use PostgreSQL's catalog rendering.
    """

    unique: bool
    method: IndexMethod
    keys: tuple[IndexKeySpec, ...]
    include_columns: tuple[str, ...] = ()
    predicate: str | None = None
    valid: bool = True
    ready: bool = True
    live: bool = True
    nulls_not_distinct: bool = False


@dataclass(frozen=True, slots=True)
class FunctionSpec:
    """Exact function signature, source, configuration, and execution properties.

    volatility is i/s/v (immutable/stable/volatile); parallel is u/r/s
    (unsafe/restricted/safe). Text and configuration order compare exactly.
    """

    identity_arguments: str
    result: str
    language: str
    volatility: FunctionVolatility
    security_definer: bool
    strict: bool
    parallel: FunctionParallelMode
    configuration: tuple[str, ...]
    source: str


@dataclass(frozen=True, slots=True)
class TriggerSpec:
    """Exact trigger catalog properties and SQL definition.

    enabled is O/D/R/A (origin/disabled/replica/always); trigger_type is
    PostgreSQL's tgtype bitmask. Application schema means public.
    """

    enabled: TriggerEnabledMode
    internal: bool
    trigger_type: int
    function_schema_is_application: bool
    function_name: str
    definition: str


_UPDATE_SEARCH_TEXT_SOURCE = (
    "\n"
    "        BEGIN\n"
    "            -- Public blob: only fields visible to everyone "
    "(title + access level),\n"
    "            -- matching exactly what filter_for_tier leaves on "
    "a redacted dataset.\n"
    "            NEW.search_text_public :=\n"
    "                COALESCE(NEW.title, '') || ' ' ||\n"
    "                COALESCE(NEW.access_level, '');\n"
    "            -- Full blob: everything. Only matched against rows "
    "the user is allowed\n"
    "            -- to fully see (tier gate applied in the query, "
    "not here).\n"
    "            NEW.search_text_full :=\n"
    "                COALESCE(NEW.title, '') || ' ' ||\n"
    "                COALESCE(NEW.description, '') || ' ' ||\n"
    "                COALESCE(NEW.project_title, '') || ' ' ||\n"
    "                COALESCE(NEW.project_description, '') || ' ' ||\n"
    "                COALESCE(array_to_string(NEW.keywords, ' '), '') "
    "|| ' ' ||\n"
    "                COALESCE(array_to_string(NEW.authors, ' '), '');\n"
    "            RETURN NEW;\n"
    "        END;\n"
    "        "
)


FUNCTION_CONTRACTS: dict[str, FunctionSpec] = {
    "update_search_text()": FunctionSpec(
        identity_arguments="",
        result="trigger",
        language="plpgsql",
        volatility="v",
        security_definer=False,
        strict=False,
        parallel="u",
        configuration=(),
        source=_UPDATE_SEARCH_TEXT_SOURCE,
    ),
}


TRIGGER_CONTRACTS: dict[str, dict[str, TriggerSpec]] = {
    "oral_history_datasets": {
        "trg_search_text": TriggerSpec(
            enabled="O",
            internal=False,
            trigger_type=23,
            function_schema_is_application=True,
            function_name="update_search_text",
            definition=(
                "CREATE TRIGGER trg_search_text BEFORE INSERT OR UPDATE "
                "ON public.oral_history_datasets FOR EACH ROW "
                "EXECUTE FUNCTION update_search_text()"
            ),
        ),
    },
    "sync_status": {},
    "ingestion_failures": {},
    "users": {},
    "totp_recovery_codes": {},
    "admin_promotion_requests": {},
    "federation_policy_state": {},
    "email_outbox": {},
    "sessions": {},
    "pending_totp_rotations": {},
}


SESSION_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "id": ColumnSpec("text", nullable=False),
    "user_id": ColumnSpec("integer", nullable=False),
    "purpose": ColumnSpec("character varying(20)", nullable=False),
    "flash_message": ColumnSpec("text", nullable=True),
    "flash_category": ColumnSpec("character varying(20)", nullable=True),
    "step_up_attempt_count": ColumnSpec(
        "smallint",
        nullable=False,
        default="0",
    ),
    "created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="CURRENT_TIMESTAMP",
    ),
    "expires_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
    ),
    "ip_address": ColumnSpec("text", nullable=True),
}


PENDING_TOTP_ROTATION_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "user_id": ColumnSpec("integer", nullable=False),
    "session_id": ColumnSpec("text", nullable=False),
    "auth_revision": ColumnSpec("bigint", nullable=False),
    "encrypted_secret": ColumnSpec("text", nullable=False),
    "confirmation_attempt_count": ColumnSpec(
        "smallint",
        nullable=False,
        default="0",
    ),
    "created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="clock_timestamp()",
    ),
    "expires_at": ColumnSpec("timestamp with time zone", nullable=False),
}


FEDERATION_POLICY_STATE_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "id": ColumnSpec("integer", nullable=False),
    "fingerprint": ColumnSpec("text", nullable=False),
    "updated_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="clock_timestamp()",
    ),
}

DATASET_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "id": ColumnSpec(
        "integer",
        nullable=False,
        identity="a",
    ),
    "uuid": ColumnSpec("text", nullable=False),
    "doi": ColumnSpec("text", nullable=True),
    "source": ColumnSpec(
        "text",
        nullable=False,
        default="'swissubase'::text",
    ),
    "title": ColumnSpec("text", nullable=True),
    "project_title": ColumnSpec("text", nullable=True),
    "description": ColumnSpec("text", nullable=True),
    "resource_description": ColumnSpec("text", nullable=True),
    "project_description": ColumnSpec("text", nullable=True),
    "bibliographical_citation": ColumnSpec("text", nullable=True),
    "authors": ColumnSpec(
        "text[]",
        nullable=False,
        default="'{}'::text[]",
    ),
    "keywords": ColumnSpec(
        "text[]",
        nullable=False,
        default="'{}'::text[]",
    ),
    "languages": ColumnSpec(
        "text[]",
        nullable=False,
        default="'{}'::text[]",
    ),
    "institutions": ColumnSpec(
        "text[]",
        nullable=False,
        default="'{}'::text[]",
    ),
    "main_disciplines": ColumnSpec(
        "text[]",
        nullable=False,
        default="'{}'::text[]",
    ),
    "resource_type": ColumnSpec("text", nullable=True),
    "version": ColumnSpec("text", nullable=True),
    "access_level": ColumnSpec("text", nullable=True),
    "visibility_tier": ColumnSpec(
        "text",
        nullable=False,
        default="'vetted'::text",
    ),
    "license_val": ColumnSpec("text", nullable=True),
    "license_url": ColumnSpec("text", nullable=True),
    "resource_proxies": ColumnSpec(
        "jsonb",
        nullable=False,
        default="'[]'::jsonb",
    ),
    "data": ColumnSpec("jsonb", nullable=True),
    "upstream_modified_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "synced_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
        default="CURRENT_TIMESTAMP",
    ),
    "search_text_public": ColumnSpec("text", nullable=True),
    "search_text_full": ColumnSpec("text", nullable=True),
}

SYNC_STATUS_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "incremental_harvest": ColumnSpec("bytea", nullable=True),
    "incremental_started_at": ColumnSpec("timestamp with time zone", nullable=True),
    "incremental_position": ColumnSpec("integer", nullable=False, default="0"),
    "incremental_affected": ColumnSpec("integer", nullable=False, default="0"),
    "incremental_failures": ColumnSpec("jsonb", nullable=False, default="'{}'::jsonb"),
    "source_cursor": ColumnSpec("timestamp with time zone", nullable=True),
    "source_fingerprint": ColumnSpec("text", nullable=True),
    "id": ColumnSpec("integer", nullable=False),
    "last_harvest_date": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "last_sync_error": ColumnSpec("text", nullable=True),
    "last_sync_error_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "last_rebuild_error": ColumnSpec("text", nullable=True),
    "last_rebuild_error_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "last_full_rebuild_date": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
}


INGESTION_FAILURE_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "source": ColumnSpec("text", nullable=False),
    "uuid": ColumnSpec("text", nullable=False),
    "message": ColumnSpec("text", nullable=False),
    "updated_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="CURRENT_TIMESTAMP",
    ),
}


USER_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "id": ColumnSpec(
        "integer",
        nullable=False,
        identity="a",
    ),
    "email": ColumnSpec("text", nullable=False),
    "display_name": ColumnSpec("text", nullable=True),
    "affiliation": ColumnSpec("text", nullable=True),
    "country": ColumnSpec("text", nullable=True),
    "password_hash": ColumnSpec("text", nullable=True),
    "auth_revision": ColumnSpec(
        "bigint",
        nullable=False,
        default="0",
    ),
    "totp_secret": ColumnSpec("text", nullable=True),
    "last_totp_step": ColumnSpec("bigint", nullable=True),
    "email_verified": ColumnSpec(
        "boolean",
        nullable=False,
        default="false",
    ),
    "email_verification_token_hash": ColumnSpec(
        "text",
        nullable=True,
    ),
    "email_verification_created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "pending_totp_secret": ColumnSpec("text", nullable=True),
    "pending_totp_created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "pending_email": ColumnSpec("text", nullable=True),
    "pending_email_token_hash": ColumnSpec("text", nullable=True),
    "pending_email_created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "password_reset_token_hash": ColumnSpec(
        "text",
        nullable=True,
    ),
    "password_reset_created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "auth_method": ColumnSpec(
        "text",
        nullable=False,
        default="'local'::text",
    ),
    "shibboleth_issuer": ColumnSpec("text", nullable=True),
    "shibboleth_subject_id": ColumnSpec("text", nullable=True),
    "federated_status": ColumnSpec("text", nullable=True),
    "federated_approved_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "federated_approved_by": ColumnSpec("integer", nullable=True),
    "access_tier": ColumnSpec(
        "text",
        nullable=False,
        default="'public'::text",
    ),
    "is_admin": ColumnSpec(
        "boolean",
        nullable=False,
        default="false",
    ),
    "is_active": ColumnSpec(
        "boolean",
        nullable=False,
        default="true",
    ),
    "created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="CURRENT_TIMESTAMP",
    ),
    "last_login": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "failed_login_count": ColumnSpec(
        "integer",
        nullable=False,
        default="0",
    ),
    "locked_until": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "lockout_notice_enqueued_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "totp_recovery_code_generation": ColumnSpec(
        "bigint",
        nullable=False,
        default="0",
    ),
    "pending_totp_recovery_code_generation": ColumnSpec(
        "bigint",
        nullable=True,
    ),
    "totp_recovery_required": ColumnSpec(
        "boolean",
        nullable=False,
        default="false",
    ),
    "totp_recovery_expires_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "totp_recovery_authorized_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "totp_recovery_auth_revision": ColumnSpec("bigint", nullable=True),
}


TOTP_RECOVERY_CODE_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "user_id": ColumnSpec("integer", nullable=False),
    "generation": ColumnSpec("bigint", nullable=False),
    "position": ColumnSpec("smallint", nullable=False),
    "code_hash": ColumnSpec("text", nullable=False),
    "password_attempt_count": ColumnSpec(
        "smallint",
        nullable=False,
        default="0",
    ),
    "created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="clock_timestamp()",
    ),
    "used_at": ColumnSpec("timestamp with time zone", nullable=True),
}


ADMIN_PROMOTION_REQUEST_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "user_id": ColumnSpec("integer", nullable=False),
    "requested_by": ColumnSpec("integer", nullable=False),
    "requested_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="clock_timestamp()",
    ),
    "expires_at": ColumnSpec("timestamp with time zone", nullable=False),
    "expected_auth_revision": ColumnSpec("bigint", nullable=False),
    "prepared_at": ColumnSpec("timestamp with time zone", nullable=True),
    "prepared_session_id": ColumnSpec("text", nullable=True),
}


EMAIL_OUTBOX_COLUMN_CONTRACT: dict[str, ColumnSpec] = {
    "terminal_outcome": ColumnSpec("text", nullable=True),
    "id": ColumnSpec(
        "bigint",
        nullable=False,
        identity="a",
    ),
    "user_id": ColumnSpec(
        "integer",
        nullable=True,
    ),
    "message_type": ColumnSpec("text", nullable=False),
    "recipient": ColumnSpec("text", nullable=False),
    "subject": ColumnSpec("text", nullable=False),
    "body_ciphertext": ColumnSpec("text", nullable=False),
    "status": ColumnSpec(
        "text",
        nullable=False,
        default="'pending'::text",
    ),
    "attempt_count": ColumnSpec(
        "integer",
        nullable=False,
        default="0",
    ),
    "next_attempt_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="CURRENT_TIMESTAMP",
    ),
    "locked_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "lock_token": ColumnSpec("uuid", nullable=True),
    "last_error": ColumnSpec("text", nullable=True),
    "created_at": ColumnSpec(
        "timestamp with time zone",
        nullable=False,
        default="CURRENT_TIMESTAMP",
    ),
    "sent_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "failed_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
    "action_token_hash": ColumnSpec("text", nullable=True),
    "expires_at": ColumnSpec(
        "timestamp with time zone",
        nullable=True,
    ),
}

TABLE_COLUMN_CONTRACTS: dict[str, dict[str, ColumnSpec]] = {
    "oral_history_datasets": DATASET_COLUMN_CONTRACT,
    "sync_status": SYNC_STATUS_COLUMN_CONTRACT,
    "ingestion_failures": INGESTION_FAILURE_COLUMN_CONTRACT,
    "users": USER_COLUMN_CONTRACT,
    "totp_recovery_codes": TOTP_RECOVERY_CODE_COLUMN_CONTRACT,
    "admin_promotion_requests": ADMIN_PROMOTION_REQUEST_COLUMN_CONTRACT,
    "federation_policy_state": FEDERATION_POLICY_STATE_COLUMN_CONTRACT,
    "email_outbox": EMAIL_OUTBOX_COLUMN_CONTRACT,
    "sessions": SESSION_COLUMN_CONTRACT,
    "pending_totp_rotations": PENDING_TOTP_ROTATION_COLUMN_CONTRACT,
}


ConstraintKind = Literal[
    "primary_key",
    "unique",
    "check",
    "foreign_key",
]

ForeignKeyAction = Literal[
    "NO ACTION",
    "RESTRICT",
    "CASCADE",
    "SET NULL",
    "SET DEFAULT",
]


@dataclass(frozen=True, slots=True)
class ConstraintSpec:
    """Exact constraint structure; unused kind-specific fields retain their defaults.

    columns and referenced_columns are ordered. check_definition uses
    PostgreSQL-rendered SQL; references_application_schema identifies public.
    """

    kind: ConstraintKind
    columns: tuple[str, ...] = ()
    check_definition: str | None = None
    referenced_table: str | None = None
    referenced_columns: tuple[str, ...] = ()
    on_update: ForeignKeyAction | None = None
    on_delete: ForeignKeyAction | None = None
    references_application_schema: bool | None = None
    deferrable: bool = False
    initially_deferred: bool = False
    validated: bool = True
    nulls_not_distinct: bool = False


DATASET_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "oral_history_datasets_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "datasets_source_uuid_key": ConstraintSpec(
        kind="unique",
        columns=("source", "uuid"),
    ),
    "datasets_source_doi_key": ConstraintSpec(
        kind="unique",
        columns=("source", "doi"),
    ),
    "datasets_visibility_tier_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((visibility_tier = ANY (ARRAY['public'::text, "
            "'registered'::text, 'vetted'::text])))"
        ),
    ),
}


SYNC_STATUS_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "sync_status_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "sync_status_incremental_position_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((incremental_position >= 0) AND "
            "((incremental_harvest IS NOT NULL) OR (incremental_position = 0))))"
        ),
    ),
    "sync_status_incremental_affected_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((incremental_affected >= 0) AND "
            "((incremental_harvest IS NOT NULL) OR (incremental_affected = 0))))"
        ),
    ),
    "sync_status_incremental_started_at_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((incremental_harvest IS NULL) OR (incremental_started_at IS NOT NULL)))"
        ),
    ),
}


INGESTION_FAILURE_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "ingestion_failures_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("source", "uuid"),
    ),
}


USER_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "users_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "users_shibboleth_identity_key": ConstraintSpec(
        kind="unique",
        columns=("shibboleth_issuer", "shibboleth_subject_id"),
    ),
    "users_local_password_required": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((auth_method <> 'local'::text) OR (password_hash IS NOT NULL)))"
        ),
    ),
    "users_lockout_notice_state_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((failed_login_count > 0) OR (lockout_notice_enqueued_at IS NULL)))"
        ),
    ),
    "users_federated_state_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((((auth_method = 'local'::text) AND "
            "(shibboleth_issuer IS NULL) AND (shibboleth_subject_id IS NULL) AND "
            "(federated_status IS NULL) AND (federated_approved_at IS NULL) AND "
            "(federated_approved_by IS NULL)) OR "
            "((auth_method = 'shibboleth'::text) AND "
            "(shibboleth_issuer IS NOT NULL) AND "
            "(shibboleth_issuer <> ''::text) AND "
            "(shibboleth_issuer = btrim(shibboleth_issuer)) AND "
            "(shibboleth_subject_id IS NOT NULL) AND "
            "(shibboleth_subject_id <> ''::text) AND "
            "(shibboleth_subject_id = btrim(shibboleth_subject_id)) AND "
            "(federated_status IS NOT NULL) AND (NOT email_verified) AND "
            "(((federated_status = 'pending'::text) AND (NOT is_active) AND "
            "(access_tier = 'public'::text) AND (NOT is_admin) AND "
            "(federated_approved_at IS NULL) AND (federated_approved_by IS NULL)) OR "
            "((federated_status = 'approved'::text) AND is_active AND "
            "(federated_approved_at IS NOT NULL) AND "
            "(federated_approved_by IS NOT NULL)) OR "
            "((federated_status = 'disabled'::text) AND (NOT is_active) AND "
            "(federated_approved_at IS NOT NULL) AND "
            "(federated_approved_by IS NOT NULL)) OR "
            "((federated_status = 'legacy_quarantined'::text) AND "
            "(NOT is_active) AND (access_tier = 'public'::text) AND "
            "(NOT is_admin) AND (federated_approved_at IS NULL) AND "
            "(federated_approved_by IS NULL))))))"
        ),
    ),
    "users_access_tier_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((access_tier = ANY (ARRAY['public'::text, "
            "'registered'::text, 'vetted'::text])))"
        ),
    ),
    "users_auth_method_check": ConstraintSpec(
        kind="check",
        check_definition=("CHECK ((auth_method = ANY (ARRAY['local'::text, 'shibboleth'::text])))"),
    ),
    "users_totp_recovery_code_generation_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((totp_recovery_code_generation >= 0) AND "
            "((pending_totp_recovery_code_generation IS NULL) OR "
            "(pending_totp_recovery_code_generation > "
            "totp_recovery_code_generation))))"
        ),
    ),
    "users_totp_recovery_state_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((((totp_recovery_expires_at IS NULL) AND "
            "(totp_recovery_authorized_at IS NULL) AND "
            "(totp_recovery_auth_revision IS NULL) AND "
            "((NOT totp_recovery_required) OR "
            "((auth_method = 'local'::text) AND "
            "(totp_secret IS NULL) AND "
            "(last_totp_step IS NULL)))) OR "
            "((auth_method = 'local'::text) AND "
            "totp_recovery_required AND "
            "(totp_secret IS NULL) AND "
            "(last_totp_step IS NULL) AND "
            "(totp_recovery_expires_at IS NOT NULL) AND "
            "(totp_recovery_authorized_at IS NOT NULL) AND "
            "(totp_recovery_auth_revision IS NOT NULL) AND "
            "(totp_recovery_authorized_at < totp_recovery_expires_at))))"
        ),
    ),
}


TOTP_RECOVERY_CODE_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "totp_recovery_codes_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("user_id", "generation", "position"),
    ),
    "totp_recovery_codes_user_generation_hash_key": ConstraintSpec(
        kind="unique",
        columns=("user_id", "generation", "code_hash"),
    ),
    "totp_recovery_codes_user_id_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("user_id",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "totp_recovery_codes_generation_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((generation > 0))",
    ),
    "totp_recovery_codes_position_check": ConstraintSpec(
        kind="check",
        check_definition='CHECK ((("position" >= 1) AND ("position" <= 10)))',
    ),
    "totp_recovery_codes_password_attempt_count_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((password_attempt_count >= 0) AND (password_attempt_count <= 3)))"
        ),
    ),
}


ADMIN_PROMOTION_REQUEST_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "admin_promotion_requests_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("user_id",),
    ),
    "admin_promotion_requests_user_id_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("user_id",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "admin_promotion_requests_requested_by_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("requested_by",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "admin_promotion_requests_different_users_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((user_id <> requested_by))",
    ),
    "admin_promotion_requests_expiry_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((expires_at > requested_at))",
    ),
    "admin_promotion_requests_prepared_state_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((((prepared_at IS NULL) AND (prepared_session_id IS NULL)) OR "
            "((prepared_at IS NOT NULL) AND (prepared_session_id IS NOT NULL) AND "
            "(prepared_at >= requested_at) AND (prepared_at < expires_at))))"
        ),
    ),
}


FEDERATION_POLICY_STATE_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "federation_policy_state_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "federation_policy_state_singleton_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((id = 1))",
    ),
}


EMAIL_OUTBOX_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "email_outbox_terminal_outcome_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((((status = 'dead'::text) = (terminal_outcome IS NOT NULL)) AND "
            "((terminal_outcome IS NULL) OR (terminal_outcome = ANY "
            "(ARRAY['cancelled'::text, 'delivery_failed'::text, "
            "'body_unreadable'::text])))))"
        ),
    ),
    "email_outbox_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "email_outbox_user_id_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("user_id",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "email_outbox_status_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((status = ANY (ARRAY['pending'::text, "
            "'sending'::text, 'sent'::text, 'dead'::text])))"
        ),
    ),
    "email_outbox_attempt_count_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((attempt_count >= 0))",
    ),
    "email_outbox_lock_state_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((status = 'sending'::text) = "
            "((locked_at IS NOT NULL) AND "
            "(lock_token IS NOT NULL))))"
        ),
    ),
    "email_outbox_sent_state_check": ConstraintSpec(
        kind="check",
        check_definition=("CHECK (((status = 'sent'::text) = (sent_at IS NOT NULL)))"),
    ),
    "email_outbox_action_metadata_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK ((((message_type = ANY "
            "(ARRAY['password_reset'::text, "
            "'email_verification'::text, "
            "'email_change_verification'::text])) "
            "AND (user_id IS NOT NULL) "
            "AND (action_token_hash IS NOT NULL) "
            "AND (expires_at IS NOT NULL)) OR "
            "((message_type = ANY "
            "(ARRAY['duplicate_registration_notice'::text, "
            "'email_change_notice'::text, "
            "'account_credential_fault_notice'::text, "
            "'account_locked_notice'::text])) "
            "AND (action_token_hash IS NULL) "
            "AND (expires_at IS NULL))))"
        ),
    ),
    "email_outbox_failed_state_check": ConstraintSpec(
        kind="check",
        check_definition=("CHECK (((status = 'dead'::text) = (failed_at IS NOT NULL)))"),
    ),
}


SESSION_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "sessions_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("id",),
    ),
    "sessions_user_id_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("user_id",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "sessions_id_user_id_key": ConstraintSpec(
        kind="unique",
        columns=("id", "user_id"),
    ),
    "sessions_purpose_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((purpose)::text = ANY "
            "((ARRAY['full'::character varying, "
            "'totp_setup'::character varying, "
            "'totp_recovery'::character varying])::text[])))"
        ),
    ),
    "sessions_flash_category_check": ConstraintSpec(
        kind="check",
        check_definition=(
            "CHECK (((flash_category)::text = ANY "
            "((ARRAY['success'::character varying, "
            "'error'::character varying, "
            "'info'::character varying])::text[])))"
        ),
    ),
    "sessions_step_up_attempt_count_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((step_up_attempt_count >= 0))",
    ),
}


PENDING_TOTP_ROTATION_CONSTRAINT_CONTRACT: dict[str, ConstraintSpec] = {
    "pending_totp_rotations_pkey": ConstraintSpec(
        kind="primary_key",
        columns=("user_id",),
    ),
    "pending_totp_rotations_user_id_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("user_id",),
        referenced_table="users",
        referenced_columns=("id",),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "pending_totp_rotations_session_user_fkey": ConstraintSpec(
        kind="foreign_key",
        columns=("session_id", "user_id"),
        referenced_table="sessions",
        referenced_columns=("id", "user_id"),
        on_update="NO ACTION",
        on_delete="CASCADE",
        references_application_schema=True,
    ),
    "pending_totp_rotations_auth_revision_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((auth_revision >= 0))",
    ),
    "pending_totp_rotations_encrypted_secret_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((encrypted_secret <> ''::text))",
    ),
    "pending_totp_rotations_confirmation_attempt_count_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((confirmation_attempt_count >= 0))",
    ),
    "pending_totp_rotations_expiry_check": ConstraintSpec(
        kind="check",
        check_definition="CHECK ((expires_at > created_at))",
    ),
}


TABLE_CONSTRAINT_CONTRACTS: dict[
    str,
    dict[str, ConstraintSpec],
] = {
    "oral_history_datasets": DATASET_CONSTRAINT_CONTRACT,
    "sync_status": SYNC_STATUS_CONSTRAINT_CONTRACT,
    "ingestion_failures": INGESTION_FAILURE_CONSTRAINT_CONTRACT,
    "users": USER_CONSTRAINT_CONTRACT,
    "totp_recovery_codes": TOTP_RECOVERY_CODE_CONSTRAINT_CONTRACT,
    "admin_promotion_requests": ADMIN_PROMOTION_REQUEST_CONSTRAINT_CONTRACT,
    "federation_policy_state": FEDERATION_POLICY_STATE_CONSTRAINT_CONTRACT,
    "email_outbox": EMAIL_OUTBOX_CONSTRAINT_CONTRACT,
    "sessions": SESSION_CONSTRAINT_CONTRACT,
    "pending_totp_rotations": PENDING_TOTP_ROTATION_CONSTRAINT_CONTRACT,
}


DATASET_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_datasets_source": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="source",
                operator_class="text_ops",
            ),
        ),
    ),
    "idx_search_text_public_trgm": IndexSpec(
        unique=False,
        method="gin",
        keys=(
            IndexKeySpec(
                definition="search_text_public",
                operator_class="gin_trgm_ops",
            ),
        ),
    ),
    "idx_search_text_full_trgm": IndexSpec(
        unique=False,
        method="gin",
        keys=(
            IndexKeySpec(
                definition="search_text_full",
                operator_class="gin_trgm_ops",
            ),
        ),
    ),
    "ix_datasets_upstream_modified_at": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="upstream_modified_at",
                operator_class="timestamptz_ops",
                descending=True,
                nulls_first=False,
            ),
            IndexKeySpec(
                definition="id",
                operator_class="int4_ops",
                descending=True,
                nulls_first=True,
            ),
        ),
    ),
    "ix_datasets_keywords_gin": IndexSpec(
        unique=False,
        method="gin",
        keys=(
            IndexKeySpec(
                definition="keywords",
                operator_class="array_ops",
            ),
        ),
    ),
    "ix_datasets_languages_gin": IndexSpec(
        unique=False,
        method="gin",
        keys=(
            IndexKeySpec(
                definition="languages",
                operator_class="array_ops",
            ),
        ),
    ),
}

SYNC_STATUS_INDEX_CONTRACT: dict[str, IndexSpec] = {}
INGESTION_FAILURE_INDEX_CONTRACT: dict[str, IndexSpec] = {}
TOTP_RECOVERY_CODE_INDEX_CONTRACT: dict[str, IndexSpec] = {}

ADMIN_PROMOTION_REQUEST_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_admin_promotion_requests_expires_at": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="expires_at",
                operator_class="timestamptz_ops",
            ),
        ),
    ),
}

FEDERATION_POLICY_STATE_INDEX_CONTRACT: dict[str, IndexSpec] = {}

USER_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_users_unverified_retention": IndexSpec(
        unique=False,
        method="btree",
        keys=(IndexKeySpec("created_at", "timestamptz_ops"), IndexKeySpec("id", "int4_ops")),
        predicate=("((auth_method = 'local'::text) AND (NOT email_verified) AND (NOT is_admin))"),
    ),
    "idx_users_email_lower": IndexSpec(
        unique=True,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="lower(email)",
                operator_class="text_ops",
            ),
        ),
    ),
}

EMAIL_OUTBOX_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_email_outbox_pending_age": IndexSpec(
        unique=False,
        method="btree",
        keys=(IndexKeySpec("created_at", "timestamptz_ops"), IndexKeySpec("id", "int8_ops")),
        predicate="(status = 'pending'::text)",
    ),
    "idx_email_outbox_recent_failures": IndexSpec(
        unique=False,
        method="btree",
        keys=(IndexKeySpec("failed_at", "timestamptz_ops"), IndexKeySpec("id", "int8_ops")),
        predicate=(
            "((status = 'dead'::text) AND (terminal_outcome = ANY "
            "(ARRAY['delivery_failed'::text, 'body_unreadable'::text])))"
        ),
    ),
    "idx_email_outbox_user_message": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(definition="user_id", operator_class="int4_ops"),
            IndexKeySpec(definition="message_type", operator_class="text_ops"),
        ),
    ),
    "idx_email_outbox_deliverable": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="next_attempt_at",
                operator_class="timestamptz_ops",
            ),
            IndexKeySpec(
                definition="id",
                operator_class="int8_ops",
            ),
        ),
        predicate="(status = 'pending'::text)",
    ),
    "idx_email_outbox_stale_claims": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="locked_at",
                operator_class="timestamptz_ops",
            ),
            IndexKeySpec(
                definition="id",
                operator_class="int8_ops",
            ),
        ),
        predicate="(status = 'sending'::text)",
    ),
    "idx_email_outbox_sent_retention": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(definition="sent_at", operator_class="timestamptz_ops"),
            IndexKeySpec(definition="id", operator_class="int8_ops"),
        ),
        predicate="(status = 'sent'::text)",
    ),
    "idx_email_outbox_dead_retention": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(definition="failed_at", operator_class="timestamptz_ops"),
            IndexKeySpec(definition="id", operator_class="int8_ops"),
        ),
        predicate="(status = 'dead'::text)",
    ),
}

SESSION_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_sessions_expires_at": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="expires_at",
                operator_class="timestamptz_ops",
            ),
        ),
    ),
    "idx_sessions_user_id": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="user_id",
                operator_class="int4_ops",
            ),
        ),
    ),
}


PENDING_TOTP_ROTATION_INDEX_CONTRACT: dict[str, IndexSpec] = {
    "idx_pending_totp_rotations_session_user": IndexSpec(
        unique=False,
        method="btree",
        keys=(
            IndexKeySpec(
                definition="session_id",
                operator_class="text_ops",
            ),
            IndexKeySpec(
                definition="user_id",
                operator_class="int4_ops",
            ),
        ),
    ),
}

TABLE_INDEX_CONTRACTS: dict[str, dict[str, IndexSpec]] = {
    "oral_history_datasets": DATASET_INDEX_CONTRACT,
    "sync_status": SYNC_STATUS_INDEX_CONTRACT,
    "ingestion_failures": INGESTION_FAILURE_INDEX_CONTRACT,
    "users": USER_INDEX_CONTRACT,
    "totp_recovery_codes": TOTP_RECOVERY_CODE_INDEX_CONTRACT,
    "admin_promotion_requests": ADMIN_PROMOTION_REQUEST_INDEX_CONTRACT,
    "federation_policy_state": FEDERATION_POLICY_STATE_INDEX_CONTRACT,
    "email_outbox": EMAIL_OUTBOX_INDEX_CONTRACT,
    "sessions": SESSION_INDEX_CONTRACT,
    "pending_totp_rotations": PENDING_TOTP_ROTATION_INDEX_CONTRACT,
}
