"""Token hashing utility and constants — shared by password reset and email verification.

Tokens themselves are generated by itsdangerous in the respective modules.
This module provides:
- hash_token(): SHA-256 hashing for DB storage so raw tokens never touch the DB
- RESET_TOKEN_MAX_AGE_SECONDS: Lifetime for password reset tokens, used by
  both itsdangerous validation and DB-level expiry checks.
"""
import hashlib

RESET_TOKEN_MAX_AGE_SECONDS = 1800  # 30 minutes

def hash_token(token: str) -> str:
    """SHA-256 hex digest of a token, for storage in the database."""
    return hashlib.sha256(token.encode()).hexdigest()